// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrutmzbjklmgtellcmby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydXRtemJqa2xtZ3RlbGxjbWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDM0MDQsImV4cCI6MjA2MDUxOTQwNH0.BKWqPs_6Vawi9RHiO2DxEhea7dX3krG0HqExarpjfnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);